### ISSUE TITLE
RAL should not 500 if no substitutions provided

### ISSUE THREAD

**Issue by lukewaite** [canvaspop/thumbor-ral#3]
Currently if you attempt to use the root alias loader but do not provide any URLs for substitution it causes the GET to 500.

```
2014-04-05 23:41:56 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1192, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1375, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/imaging.py", line 30, in get
    if not self.validate(kw['image']):
  File "/usr/local/lib/python2.7/dist-packages/thumbor/handlers/__init__.py", line 256, in validate
    is_valid = self.context.modules.loader.validate(self.context, path)
  File "/usr/local/lib/python2.7/dist-packages/thumbor_root_alias_loader/__init__.py", line 21, in validate
    url = _prepare(context, url)
  File "/usr/local/lib/python2.7/dist-packages/thumbor_root_alias_loader/__init__.py", line 40, in _prepare
    alias = config.get(urllib.unquote(parts[0]), None)
AttributeError: 'list' object has no attribute 'get'
```

**Comment by lukewaite** [comment]
Different issue.
